### ISSUE TITLE
Todos 2.0

### ISSUE THREAD

**Issue by Zaitonn** [SereinDev/Serein#109]
# Todos 2.0

- [x] 多服务器配置管理
  - [x] 导入导出配置
  - [x] 部分个性化
- [ ] OneBot支持
  - [ ] #83 （待定）
  - [x] ~~单独拆分为Nuget库~~
- [x] 匹配
  - [x] 实现限制参数功能
- [ ] 实现iPanel功能
- [x] ~~SSH控制服务器~~
  - [x] ~~通过ssh实现Serein.Cli大部分功能~~
  - [x] ~~尝试支持交互性的读入输出 （使用`Spectre.Console`的`IAnsiConsole`接口）~~
- [ ] Ui
  - [x] ~~Plus版使用`WinUi3`而不是第三方wpf库~~
  - [x] 实现Lite版的Winform Ui
  - [ ] 添加插件市场
- [ ] Http服务器
  - [ ] RESTFUL Apis
  - [ ] WebSocket服务器广播
- [x] 优化插件系统
  - [x] ~~暂时删除Net插件支持~~
  - [x] 更改插件结构（待定）
    - 单文件 `plugins/*.js`
    - 多文件
      - `plugins/*/index.js`
      - `plugins/*/*.js`
      - `plugins/*/plugininfo.json`
  - [x] 优化插件导入和导出功能
  - [x] 优化加载逻辑
- [x] 升级到[.Net 8](https://dotnet.microsoft.com/zh-cn/download/dotnet/8.0)
- [x] 使用[`Hardware.Info`](https://github.com/Jinjinov/Hardware.Info)代替原`SystemInfo`
- [ ] 重构文档
  - [ ] 细化介绍条目
  - [x] 升级到v3
  - [x] ~~合并扩展市场~~ 已拆分至https://sereincommunity.github.io/

## 依赖

```diff
+ EmbedIO
+ FxSsh
+ GitHubActionsTestLogger
+ Hardware.Info
+ Octokit
+ System.CommandLine

- LiteDB
- SystemInfoLibrary-devel
```
